### ISSUE TITLE
clean up hardcoded urls in styles

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#276]
there are a variety of hardcoded urls used for things like icons in our styles:
```scss
span[role=tooltip]::before { // the pointing triangle
    content: url('/static/img/icons/informationTriangle.svg');
}
```
we can make these paths less brittle by using variables, e.g.
```scss
$iconsPath: '/static/img/icons'
```
or even writing a mixin/function:
```scss
@function asset-path($filename) {
    @return '/static/img/' + $filename // or something like this
}
```
