### ISSUE TITLE
style/consistency changes

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#439]
# testing notes

- en-dash/spacing: this should be consistent everywhere. the only place I found that wasn't correct was the sort options on the members search; leave a comment if there are any others remaining.
- the page selection dropdown on the members search now should now have the "pointer" cursor to indicate it's interactive and contrast with the sort dropdown, which is not interactive. I unfortunately can't make the sort dropdown non-focusable, because then non-sighted users would likely never hear it read.
- membership activities should no longer be sortable by category; the tooltip remains.
- the gender filter on members search should now say "Unidentified" instead of "Unknown".
- analysis essay dates should now use the AP abbreviation style.

# dev notes
- [x] Use en-dash and spaces everywhere for ranges (sort a-z, dates, birth/death label)
- [x] Make member sort by nonfocusable; give displaying pointer mouse icon
- [x] Make membership activities not sortable by category (disable other sort options?)
- [x] Revise text for “unknown” gender filter - use unidentified
- [x] Revise choice filter (gender) display on mobile to avoid overlap
- [x] Abbreviate month names on analysis essay tiles

**Comment by thatbudakguy** [comment]
```css
/* main-ffa9cb02c122c3de6ec7.min.css | https://test-shakespeareandco.cdh.princeton.edu/static/css/main-ffa9cb02c122c3de6ec7.min.css */

@media (max-width: calc(767px)) {
.search-form fieldset.facet.choice label {
  font-size: .7rem;
}

  .search-form fieldset.facet.choice .choice {
    flex: auto;
  }

.search-form fieldset.facet.choice label .count {
  font-size: .5rem;
  width: 100%;
  text-align: right;
  padding-right: .5rem;
}

.search-form fieldset.facet.choice label::before {
  width: .5rem;
  height: .5rem;
}
}
```
